// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2T6pNNhWvDxDtwJ3c7ekSJ_HJ-S7qUM',
    appId: '1:919324671992:android:0caaa40bda7700dd0be00d',
    messagingSenderId: '919324671992',
    projectId: 'ecostep-plz',
    storageBucket: 'ecostep-plz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1AwfmhZmzfRcN_ehB6YETN0G4gF8y3lY',
    appId: '1:919324671992:ios:a6996d59bfba18c60be00d',
    messagingSenderId: '919324671992',
    projectId: 'ecostep-plz',
    storageBucket: 'ecostep-plz.firebasestorage.app',
    androidClientId: '919324671992-3nlep8ohjeqeb56v14hnpcbla8ppdp94.apps.googleusercontent.com',
    iosClientId: '919324671992-tv0ra9km35lgkjs5tgq4sghtv1hab4j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecostepApplication',
  );

}